[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.20.1"
tree-sitter-cli = "0.20.1"
rusted_gumtree_core = { path = "../core" }
rusted_gumtree_gen_ts_java = { path = "../gen/tree-sitter/java" }