[package]
name = "hyperast_gen_ts_ts"
version = "0.3.0"
edition = "2024"

[dependencies]
tree-sitter = { workspace = true, optional = true }
# tree-sitter = { path="../../../../tree-sitter/lib", version="0.20", optional = true}
# tree-sitter-typescript = { git = "https://github.com/quentinLeDilavrec/tree-sitter-typescript", rev = "eee64b9ea005d2641cfce5b0a81404a9c8877740", version = "0.20.5", optional = true }
tree-sitter-typescript = { version = "0.23.0", optional = true }
atomic-counter = "1.0.1"
num = "0.4.0"
bitvec = "1.0.1"
controlled-option = "0.4.1"
cfg-if = "1.0"
hashbrown = { version = "0.14.5", default-features = false, optional = true }
log = { version = "0.4.6" }                                                   #, features = ["max_level_debug", "release_max_level_warn"] }

hyperast = { workspace = true, default-features = false }

libc = "0.2"

legion = { version = "0.4.0", optional = true }
tuples = "=1.4.1"

enumset = "1.0.8"

serde = { version = "1.0.130" }

[dev-dependencies]
pretty_assertions = "1.0.0"
env_logger = "0.11.3"

[features]
default = ["impl"]
legion = ["hyperast/legion", "dep:legion"]
impl = [
    "hyperast/jemalloc",
    "legion",
    "hyperast/native",
    "dep:hashbrown",
    "hashbrown?/ahash",
    "dep:tree-sitter",
    "dep:tree-sitter-typescript",
    "hyperast/ts",
]
