[workspace]
members = ["gumtree", "gumtree", "cvs/git","client","benchmark","tree-sitter_types","ref-mining-evaluation",
"gen/tree-sitter/*",
]
exclude = ["gen/tree-sitter/java/tree-sitter-java"]
default-members = ["gumtree", "gen/tree-sitter/java", "gen/tree-sitter/xml", "cvs/git","benchmark","ref-mining-evaluation"]