[workspace]
members = [
    "hyper_diff",
    "hyper_ast",
    "gen/tree-sitter/*",
    "cvs/git",
    "client",
    "benchmark",
    "ref-mining-evaluation",
    "benchmark_diffs",
    "hyper_app",
    "hyperast_wasm",
    "egui_addon",
    "polyglote",
    "tsquery",
]
exclude = ["gen/tree-sitter/java/tree-sitter-java"]
default-members = [
    "hyper_ast",
    "hyper_diff",
    "gen/tree-sitter/java",
    "gen/tree-sitter/cpp",
    "gen/tree-sitter/xml",
    "gen/tree-sitter/ts",
    "gen/tree-sitter/query",
    "cvs/git",
    "benchmark",
    "hyperast_wasm",
    "ref-mining-evaluation",
    "benchmark_diffs",
    "polyglote",
    "tsquery",
]
