cargo-features = ["profile-rustflags"]

[package]
name = "hyper_ast_benchmark_diffs"
version = "0.2.0"
edition = "2021"
autobins = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = { workspace = true }
hyper_ast = { workspace = true }
hyper_diff = { workspace = true }
hyper_ast_cvs_git = { workspace = true }
hyper_ast_gen_ts_java = { workspace = true }
hyper_ast_gen_ts_xml = { workspace = true }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.79"
env_logger = "0.11.3"
log = { version = "0.4.6", features = [
    "max_level_debug",
    "release_max_level_warn",
] }

cfg-if = "1.0"

num-traits = "0.2.14"
tuples = "=1.4.1"

rayon = "1.5.2"
hashbrown = { version = "0.13.1", features = ["rayon"] }
byteorder = "1.4.3"
bitvec = "1.0.1"
md5 = "0.7.0"

pprof = { version = "0.10", features = ["prost-codec", "flamegraph"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.5.0"

# [build-dependencies]

[dev-dependencies]
hyper_ast_gen_ts_java = { workspace = true }

# [[bin]]
# name = "window_combination"
# path = "binwindow_combination.rs"
