
[package]
name = "hyperast_benchmark_diffs"
version = "0.3.0"
edition = "2024"
autobins = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = { workspace = true }
hyperast = { workspace = true }
hyper_diff = { workspace = true }
hyperast_vcs_git = { workspace = true }
hyperast_gen_ts_java = { workspace = true }
hyperast_gen_ts_xml = { workspace = true }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.79"
env_logger = "0.11.3"
log = { version = "0.4.6", features = [
    "max_level_debug",
    "release_max_level_warn",
] }

cfg-if = "1.0"

num-traits = "0.2.14"
tuples = "=1.4.1"

rayon = "1.5.2"
hashbrown = { version = "0.13.1", features = ["rayon"] }
byteorder = "1.4.3"
bitvec = "1.0.1"
md5 = "0.7.0"

pprof = { version = "0.10", features = ["prost-codec", "flamegraph"] }

const-chunks = "0.3.0"
memory-stats = "1.2.0"

jemallocator = { package = "tikv-jemallocator", version = "0.5.0", optional = true }
jemalloc-ctl = { package = "tikv-jemalloc-ctl", version = "0.5.4", optional = true }
regex = "1.11.1"
tabled = "0.19.0"
chrono = "0.4.41"
walkdir = "2.5.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { package = "tikv-jemallocator", version = "0.5.0" }

# [build-dependencies]

[dev-dependencies]
hyperast_gen_ts_java = { workspace = true }
criterion = { version = "0.4", features = [
    "rayon",
    "plotters",
    "cargo_bench_support",
    "html_reports",
    # "real_blackbox",
] }


[[bench]]
name = "cd_runtime"
harness = false

[[bench]]
name = "cd_memory_criterion"
harness = false

[[bin]]
name = "cd_memory"
path = "benches/cd_memory.rs"


[[bin]]
name = "cd_memory_jemalloc"
path = "benches/cd_memory_jemalloc.rs"

[[bin]]
name = "cd_memory_system_time"
path = "benches/cd_memory_system_time.rs"

[[bin]]
name = "cd_memory_system_instruments"
path = "benches/cd_memory_system_instruments.rs"


[[bin]]
name = "cd_memory_custom"
path = "benches/cd_memory_custom.rs"

[[bin]]
name = "algorithm_runner"
path = "benches/algorithm_runner.rs"

[[bin]]
name = "cd_hyperparameter_tuner"
path = "src/bin/cd_hyperparameter_tuner.rs"

[profile.release]
debug = true
