[package]
name = "rusted_gumtree_gen_ts_javascript"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.20.0"
tree-sitter-javascript = { path = "tree-sitter-javascript", version="0.20.0" }
hyper_ast = { path = "../../../hyper_ast" }

[build-dependencies]
cc="*"