[package]
name = "rusted_gumtree_gen_ts_html"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.20.0"
rusted_gumtree_core = { path = "../../../core" }


libc = "0.2"

[build-dependencies]
cc = "*"

[dev-dependencies]
pretty_assertions = "1.0.0"