[package]
name = "hyperast_gen_ts_tsquery"
version = "0.3.0"
edition = "2024"

[dependencies]
tree-sitter = { workspace = true, optional = true }
tree-sitter-query = { git = "https://github.com/tree-sitter-grammars/tree-sitter-query", rev = "d25e8d183f319497b8b22a2a1585975b020da722", version = "0.3.0", optional = true }
atomic-counter = "1.0.1"
num = "0.4.0"
bitvec = "1.0.1"
controlled-option = "0.4.1"
cfg-if = "1.0"
hashbrown = { version = "0.14.5", default-features = false, optional = true }
log = { version = "0.4.6" }                                                                                                                                                     #, features = ["max_level_debug", "release_max_level_warn"] }

hyperast = { workspace = true, default-features = false }
hyperast_tsquery = { workspace = true, optional = true }

libc = "0.2"

legion = { version = "0.4.0", optional = true }
tuples = "=1.4.1"

enumset = "1.0.8"

serde = { version = "1.0.130" }

rayon = { version = "1.10.0", optional = true }

petgraph = { version = "0.7.1", optional = true }

[dev-dependencies]
pretty_assertions = "1.0.0"
env_logger = "0.11.3"
hyperast_gen_ts_cpp = { workspace = true }
tree-sitter-java = "0.23.0"
hyperast_gen_ts_xml = { workspace = true }
criterion = { version = "0.6.0", features = [
    "rayon",
    "plotters",
    "cargo_bench_support",
    "html_reports",
] }

[lib]
bench = false

[[bench]]
name = "capture_names"
harness = false


[features]
default = ["impl"]
legion = ["hyperast/legion", "dep:legion"]
impl = [
    "hyperast/jemalloc",
    "legion",
    "dep:hashbrown",
    "hyperast/native",
    "hashbrown?/ahash",
    "dep:tree-sitter",
    "dep:tree-sitter-query",
    "dep:hyperast_tsquery",
]
synth_par = ["dep:rayon", "hashbrown?/rayon"]
lattice = ["dep:petgraph"]
