[book]
authors = ["Paul ADAM"]
language = "en"
multilingual = false
src = "src"
title = "HyperAST book"

[output.html.fold]
enable = true

[output.html]
git-repository-url = "https://github.com/HyperAST"