[package]
name = "hyper_ast_gen_ts_cpp"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = { version = "0.22.2", optional = true }
# tree-sitter = { path="../../../../tree-sitter/lib", version="0.20", optional = true}
# tree-sitter-java = {path="tree-sitter-java", version="0.20.0"}
tree-sitter-cpp = { git = "https://github.com/quentinLeDilavrec/tree-sitter-cpp", version = "0.22", rev = "e0a743cf117b28f1ed86f205b4c722e02f5035e1", optional = true }
# tree-sitter-cpp = { path="tree-sitter-cpp", version="0.20", optional = true}
# tree-sitter-cpp = { path="../../../../tree-sitter-cpp", version="0.22", optional = true}
# tree-sitter-cpp = { version = "0.22.0", optional = true }
atomic-counter = "1.0.1"
num = "0.4.0"
bitvec = "1.0.1"
controlled-option = "0.4.1"
cfg-if = "1.0"
hashbrown = { version = "0.14.5", default-features = false, optional = true }
log = { version = "0.4.6" }

hyper_ast = { path = "../../../hyper_ast", default-features = false }

libc = "0.2"

legion = { version = "0.4.0", optional = true }
tuples = "=1.4.1"

enumset = "1.0.8"

serde = { version = "1.0.130" }

[dev-dependencies]
pretty_assertions = "1.0.0"
env_logger = "0.11.3"

[features]
default = ["impl"]
legion = ["hyper_ast/legion", "dep:legion"]
impl = [
    "hyper_ast/jemalloc",
    "legion",
    "hyper_ast/native",
    "dep:hashbrown",
    "hashbrown?/ahash",
    "dep:tree-sitter",
    "dep:tree-sitter-cpp",
]
