[package]
name = "hyperast_gen_ts_cpp"
version = "0.3.0"
edition = "2024"

[dependencies]
tree-sitter = { workspace = true, optional = true }
# tree-sitter = { path="../../../../tree-sitter/lib", version="0.20", optional = true}
# tree-sitter-java = {path="tree-sitter-java", version="0.20.0"}
# tree-sitter-cpp = { path="tree-sitter-cpp", version="0.20", optional = true}
# tree-sitter-cpp = { path="../../../../tree-sitter-cpp", version="0.23.1", optional = true}
atomic-counter = "1.0.1"
num = "0.4.0"
bitvec = "1.0.1"
controlled-option = "0.4.1"
cfg-if = "1.0"
hashbrown = { version = "0.14.5", default-features = false, optional = true }
log = { version = "0.4.6" }

hyperast = { path = "../../../crates/hyper_ast", default-features = false }
# hyperast = { workspace = true, default-features = false } # issue with hyper_app + wasm

libc = "0.2"

legion = { version = "0.4.0", optional = true }
tuples = "=1.4.1"

enumset = "1.0.8"

serde = { version = "1.0.130" }

tree-sitter-cpp = { version = "0.23.1", optional = true }
tree-sitter-cpp_alt = { package = "tree-sitter-cpp", git = "https://github.com/quentinLeDilavrec/tree-sitter-cpp", version = "0.23.1", rev = "81216ae5ba2778522eee06392cf0352b9410e4fe", optional = true }


[dev-dependencies]
pretty_assertions = "1.0.0"
env_logger = "0.11.3"
hyperast_tsquery = { workspace = true }

[features]
default = ["impl"]
legion = ["hyperast/legion", "dep:legion"]
impl_intern = [
    "hyperast/jemalloc",
    "legion",
    "hyperast/native",
    "dep:hashbrown",
    "hashbrown?/ahash",
    "dep:tree-sitter",
    "hyperast/ts",
]
impl = ["impl_intern", "dep:tree-sitter-cpp"]
alt_grammar = []
impl_alt_grammar = ["alt_grammar", "impl_intern", "dep:tree-sitter-cpp_alt"]
