name: Dispatcher
on:
  push:
    branches:
      - main

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            --request POST \
            --data '{"event_type": "updated_book", "client_payload": { "foo": "bar" }}' https://api.github.com/repos/HyperAST/HyperAST.github.io/dispatches
#   deploy:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write  # To push a branch 
#       pull-requests: write  # To create a PR from that branch
#     steps:
#     - uses: actions/checkout@v3
#       with:
#         fetch-depth: 0
#     - name: Install latest mdbook
#       run: |
#         tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
#         url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
#         mkdir mdbook
#         curl -sSL $url | tar -xz --directory=./mdbook
#         echo `pwd`/mdbook >> $GITHUB_PATH
#     - name: Deploy GitHub Pages
#       run: |
#         # This assumes your book is in the root of your repository.
#         # Just add a `cd` here if you need to change to another directory.
        
#         cd book
#         mdbook build

#         git config --global user.name "Deploy book from CI into github page"
#         git config --global user.email ""
#         # git clone git@github.com:HyperAST/HyperAST.github.io.git 
#         ssh-agent sh -c 'echo "${{ secrets.GH_PAGE_SHA }}" | ssh-add - && git clone git@github.com:HyperAST/HyperAST.github.io.git'
#         cd HyperAST.github.io

#         # Delete the ref to avoid keeping history.
#         git update-ref -d refs/heads/master
#         rm -rf *
#         mv ../book/* .
#         git add .
#         git commit -m "Deploy $GITHUB_SHA to Hyper.github.io"
#         git push --force
