name: Build and Publish Docker Image

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get version
      - name: Get the version
        id: get_version
        run: echo "VERSION={$(echo $GITHUB_REF | cut -d / -f 3)}" >> $GITHUB_OUTPUT
     
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Nix
      - name: Set up Nix
        uses: cachix/install-nix-action@v15

      # Build the Docker image using nix
      - name: Build Docker image with Nix
        run: |
          nix build .#hyperast-dockerImage --no-link --out-link HyperAST-${{ steps.get_version.outputs.VERSION }}.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            HyperAST-${{ steps.get_version.outputs.VERSION }}.tar.gz
            LICENSE
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
