[package]
name = "hyper_ast_gen_ts_xml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = { version = "0.20.9", optional = true }
tree-sitter-xml = { git = "https://github.com/quentinLeDilavrec/tree-sitter-xml", version = "0.20.0", optional = true }
hyper_ast = { path = "../../../hyper_ast", default-features = false }


libc = "0.2"


legion = { version = "0.4.0", optional = true }
tuples = "=1.4.1"

[build-dependencies]
cc = "*"

[dev-dependencies]
pretty_assertions = "1.0.0"

[features]
default = ["impl"]
legion = ["hyper_ast/legion", "dep:legion"]
impl = [
    "hyper_ast/jemalloc",
    "legion",
    "dep:tree-sitter",
    "dep:tree-sitter-xml",
]
