[package]
name = "hyperast_gen_ts_xml"
version = "0.3.0"
edition = "2024"

[dependencies]
tree-sitter = { workspace = true, optional = true }
# tree-sitter-xml = { git = "https://github.com/quentinLeDilavrec/tree-sitter-xml", rev="1f06da3921a23255d851c62ca81ce2b176c6eb55", version = "0.20.0", optional = true }
tree-sitter-xml = { version = "0.7.0", optional = true }
hyperast = { path = "../../../crates/hyper_ast", default-features = false }
# hyperast = { workspace = true, default-features = false } # issue with hyper_app + wasm

hashbrown = { version = "0.14.5", default-features = false, optional = true }
log = { version = "0.4.6" }

num = "0.4.0"

libc = "0.2"

legion = { version = "0.4.0", optional = true }
tuples = "=1.4.1"

[dev-dependencies]
pretty_assertions = "1.0.0"

[features]
default = ["impl"]
legion = ["hyperast/legion", "dep:legion"]
impl = [
    "hyperast/jemalloc",
    "legion",
    "hyperast/native",
    "dep:hashbrown",
    "hashbrown?/ahash",
    "dep:tree-sitter",
    "dep:tree-sitter-xml",
    "hyperast/ts",
]
