[package]
name = "hyper_ast_gen_ts_xml"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = { version = "0.22.2", optional = true }
# tree-sitter-xml = { git = "https://github.com/quentinLeDilavrec/tree-sitter-xml", rev="1f06da3921a23255d851c62ca81ce2b176c6eb55", version = "0.20.0", optional = true }
tree-sitter-xml = { version = "0.6.2", optional = true }
hyper_ast = { path = "../../../hyper_ast", default-features = false }

hashbrown = { version = "0.14.5", default-features = false, optional = true }

num = "0.4.0"

libc = "0.2"

legion = { version = "0.4.0", optional = true }
tuples = "=1.4.1"

[dev-dependencies]
pretty_assertions = "1.0.0"

[features]
default = ["impl"]
legion = ["hyper_ast/legion", "dep:legion"]
impl = [
    "hyper_ast/jemalloc",
    "legion",
    "hyper_ast/native", 
    "dep:hashbrown",
    "hashbrown?/ahash",
    "dep:tree-sitter",
    "dep:tree-sitter-xml",
]
